# Production compose: uses pre-built images from GHCR instead of local build.
# Set COMPOSE_IMAGE_BASE=ghcr.io/owner/repo (e.g. ghcr.io/myorg/ghost2lead-backend).
services:
  api:
    image: ${COMPOSE_IMAGE_BASE}/api:latest
    ports:
      - 8080:8000
    command: ["sh", "scripts/entrypoint.sh"]
    env_file: .env
    environment:
      DATABASE_SERVER: db
      DATABASE_NAME: ghost2lead
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      celery:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
    healthcheck:
      test: ["CMD", "scripts/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ghost2lead
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  celery:
    image: ${COMPOSE_IMAGE_BASE}/worker:latest
    command: celery -A app.worker.tasks:celery_app worker --loglevel=info
    env_file: .env
    environment:
      DATABASE_SERVER: db
      DATABASE_NAME: ghost2lead
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"

volumes:
  postgres_data: {}
  redis_data: {}
