"""add last event processed timestamp and behaviors to lead table

Revision ID: 2db98bf354ff
Revises: b41e24ce7363
Create Date: 2026-02-23 13:04:07.612449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2db98bf354ff'
down_revision: Union[str, Sequence[str], None] = 'b41e24ce7363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_processed_event_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('behaviors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'behaviors')
    op.drop_column('leads', 'last_processed_event_timestamp')
    # ### end Alembic commands ###
