"""add profile and actions to lead table

Revision ID: 882a74a8c1e8
Revises: 2db98bf354ff
Create Date: 2026-02-24 18:11:41.630740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '882a74a8c1e8'
down_revision: Union[str, Sequence[str], None] = '2db98bf354ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'actions')
    op.drop_column('leads', 'profile')
    op.drop_column('leads', 'enriched_at')
    # ### end Alembic commands ###
