"""remove ip and signup from lead table

Revision ID: b41e24ce7363
Revises: bce1b2ff1ea5
Create Date: 2026-02-21 17:04:53.671993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b41e24ce7363'
down_revision: Union[str, Sequence[str], None] = 'bce1b2ff1ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'ip_address_encrypted')
    op.drop_column('leads', 'signed_up_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('signed_up_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('ip_address_encrypted', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
